### ISSUE TITLE
有些鸡贼的院校的教务网站会放在某个目录下

### ISSUE THREAD

**Issue by RSSYLY** [jokerwho/zfn_api#3]
例如是 http://jw.sbxxx.edu.cn/jwglxt/ ，这导致登陆界面是 http://jw.sbxxx.edu.cn/jwglxt/xtgl/login_slogin.html ，而目前程序中的 urljoin() 方法会将原路径覆盖掉。解决方法是将路径使用./，都改为 urljoin(self.base_url, "./xxx")

**Comment by Yilimmilk** [comment]
在传入base_url的时候干脆不传入最后一个/即可，也就是传入：http://jw.sbxxx.edu.cn/jwglxt

**Comment by whx1024** [comment]
亲测楼主方法可用 [Yilimmilk]方法不可用。
